---
title: "Citibikes"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}

library(tidyverse)
library(knitr)
library(modelr)
library(lubridate)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `trips_per_day.tsv` file
```{r load-data}

trips <- read_tsv('trips_per_day.tsv')

```

```{r partition-data}

shuffled <- sample_frac(trips, 1, replace = F)
trainingData <- shuffled[1:I(.8*nrow(trips)), 1:8]
validationData <- shuffled[I(.8*nrow(trips)+1):nrow(trips), 1:8]

```

```{r modeling}

lm.fitT <- lm(num_trips ~ tmin, data = trainingData)

trainingData <- add_predictions(trainingData, lm.fitT)
validationData <- add_predictions(validationData, lm.fitT)

validationData %>% ggplot() +
  geom_line(data = trainingData, aes(x = tmin, y = pred), color = "blue") +
  geom_point(aes(x = tmin, y = num_trips), color = "red") +
  geom_point(data = trainingData, aes(x = tmin, y = num_trips), color = "green")

cor(trainingData$tmin, trainingData$num_trips) ^ 2
#rsquare(lm.fitT, trainingData)
sqrt(mean((trainingData$pred - trainingData$num_trips)^2))
#rmse(lm.fitT, trainingData)

cor(validationData$num_trips, validationData$pred) ^ 2
sqrt(mean((validationData$pred - validationData$num_trips)^2))
#rmse(lm.fitT, validationData)

```

```{r quadratic}

lm.fitQ <- lm(num_trips ~ tmin + I(tmin^2), data = trainingData)

trainingData <- add_predictions(trainingData, lm.fitQ, var = "pred2")
validationData <- add_predictions(validationData, lm.fitQ, var = "pred2")

validationData %>% ggplot() +
  geom_line(data = trainingData, aes(x = tmin, y = pred2), color = "black") +
  geom_point(aes(x = tmin, y = num_trips), color = "red") +
  geom_point(data = trainingData, aes(x = tmin, y = num_trips), color = "green")

rmse(lm.fitQ, trainingData)
rsquare(lm.fitQ, trainingData)

rmse(lm.fitQ, validationData)
rsquare(lm.fitQ, validationData)

```

```{r polynomial-errors}

K <- c(1:8)

training_r_sq <- c()
validation_r_sq <- c()
training_rmse <- rep(0, 8)
validation_rmse <- rep(0, 8)

for (k in K){
  lm.fit <- lm(num_trips ~ poly(tmin, k, raw = T), data = trainingData)
  training_r_sq[k] <- rsquare(lm.fit, trainingData)
  validation_r_sq[k] <- rsquare(lm.fit, validationData)
  training_rmse[k] <- rmse(lm.fit, trainingData)
  validation_rmse[k] <- rmse(lm.fit, validationData)
}

ggplot() + 
  geom_line(aes(x = K, y = training_r_sq), color = "red") + 
  geom_line(aes(x = K, y = validation_r_sq), color = "blue") +
  xlab("Polynomial Order") +
  ylab("R-Squared")

 # ggplot() + 
 #   geom_line(aes(x = K, y = training_rmse), color = "red") + 
 #   geom_line(aes(x = K, y = validation_rmse), color = "blue")

```

```{r model 4}

lm.fit4 <- lm(num_trips ~ poly(tmin, 4, raw = T), data = trainingData)

trainingData <- add_predictions(trainingData, lm.fit4, var = "pred4")
validationData <- add_predictions(validationData, lm.fit4, var = "pred4")

validationData %>% ggplot() +
  geom_line(data = trainingData, aes(x = tmin, y = pred4), color = "blue") +
  geom_point(aes(x = tmin, y = num_trips), color = "red") +
  geom_point(data = trainingData, aes(x = tmin, y = num_trips), color = "green")

```

```{r k-fold}

folded <- sample_frac(trips, 1, replace = F)
folded <- folded %>% mutate(fold = ((row_number() %% 5) + 1))

training_rmse <- rep(0, 8)
validation_rmse <- rep(0, 8)

for (k in 1:8){
  
  tRMSE <- rep(0, 5)
  vRMSE <- rep(0, 5)
  
  for (f in 1:5){
    trainingD <- folded %>% filter(fold != f)
    validationD <- folded %>% filter(fold == f)
  
    lm.fitF <- lm(num_trips ~ poly(tmin, k, raw = T), data = trainingD)
  
    tRMSE[f] <- rmse(lm.fitF, trainingD)
    vRMSE[f] <- rmse(lm.fitF, validationD)
  }

  training_rmse[k] <- mean(tRMSE)
  validation_rmse[k] <- mean(vRMSE)
}


ggplot() + geom_line(aes(x = 1:8, y = training_rmse), color = "red") +
  geom_line(aes(x = 1:8, y = validation_rmse), color = "blue")

```

```{r prediction}

holidays <- read_csv("https://gist.githubusercontent.com/shivaas/4758439/raw/b0d3ddec380af69930d0d67a9e0519c047047ff8/US%2520Bank%2520holidays", col_names = c("row_num", "date", "holiday"))

trip_data <- left_join(trips, holidays, by = c("ymd" = "date"))

trip_data <- trip_data %>% 
  mutate(is_holiday = !(is.na(holiday))) %>%
  mutate(weekday = wday(ymd)) %>%
  mutate(weekend = (weekday == 1 | weekday == 7)) %>%
  dplyr::select(ymd, prcp, snwd, snow, tmax, tmin, is_holiday, num_trips, weekend)

shuffled <- sample_frac(trip_data, 1, replace = F)
trainingDataP <- shuffled[1:I(.8*nrow(trips)), 1:9]
validationDataP <- shuffled[I(.8*nrow(trips)+1):nrow(trips), 1:9]

lm.fit <- lm(num_trips~.-ymd -tmin -snow, data = trainingDataP)

trip_data <- add_predictions(trip_data, lm.fit)

ggplot(data = trip_data) +
  geom_point(aes(x = ymd, y = num_trips)) +
  geom_line(aes(x = ymd, y = pred))

validationDataP <- add_predictions(validationDataP, lm.fit)
rmseV <- sqrt(mean((validationDataP$pred - validationDataP$num_trips)^2))

```